export const LOCAL_CODE_INTEL_SKILL = [
  '---',
  'name: local-code-intel',
  'description: >-',
  '  Find code, symbols, and repository context through the local-code-intelligence',
  '  MCP server (a local, always-current index) instead of Grep/Glob or reading whole',
  '  files. Use when locating code, exploring a repository, or answering where or how',
  '  something works.',
  '---',
  '',
  '# Local code intelligence',
  '',
  'MCP namespace: `user-local-code-intelligence`. Replies are exact current source plus which parts of the request they cover.',
  '',
  '1. `get_task_context` once with the whole request (`mode: deep` for cross-cutting work).',
  '2. `complete` means answer from it. Otherwise run only its `Next` calls, then answer.',
  '3. More lines: `get_file_context` with `ranges: ["path:120-168"]` and `ctx`; skip code you already have.',
  '4. Exact names: `search_symbol`; occurrences: `find_references`.',
  '5. Grep/Glob/Read a specific path only for `missing` parts or a stale or unindexed repo.',
  '',
  'Unindexed repo: run `code-intel setup --repo <path>` and retry.',
  ''
].join('\n');
